package com.jgkj.bxxc.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jgkj.bxxc.bean.entity.SubProjectEntity.SubProjectEntity;
import com.jgkj.bxxc.bean.entity.Sub4ProjectEntity.Sub4ProjectEntity;

import com.jgkj.bxxc.db.SubProjectEntityDao;
import com.jgkj.bxxc.db.Sub4ProjectEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subProjectEntityDaoConfig;
    private final DaoConfig sub4ProjectEntityDaoConfig;

    private final SubProjectEntityDao subProjectEntityDao;
    private final Sub4ProjectEntityDao sub4ProjectEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subProjectEntityDaoConfig = daoConfigMap.get(SubProjectEntityDao.class).clone();
        subProjectEntityDaoConfig.initIdentityScope(type);

        sub4ProjectEntityDaoConfig = daoConfigMap.get(Sub4ProjectEntityDao.class).clone();
        sub4ProjectEntityDaoConfig.initIdentityScope(type);

        subProjectEntityDao = new SubProjectEntityDao(subProjectEntityDaoConfig, this);
        sub4ProjectEntityDao = new Sub4ProjectEntityDao(sub4ProjectEntityDaoConfig, this);

        registerDao(SubProjectEntity.class, subProjectEntityDao);
        registerDao(Sub4ProjectEntity.class, sub4ProjectEntityDao);
    }
    
    public void clear() {
        subProjectEntityDaoConfig.clearIdentityScope();
        sub4ProjectEntityDaoConfig.clearIdentityScope();
    }

    public SubProjectEntityDao getSubProjectEntityDao() {
        return subProjectEntityDao;
    }

    public Sub4ProjectEntityDao getSub4ProjectEntityDao() {
        return sub4ProjectEntityDao;
    }

}
